1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np
arr = np.random.uniform(0, 20, (4, 7))#заполнение массива размерности 4 на 7 случайными дробными числами в диапазоне от 0 до 20
arr_norm = (arr - arr.min())/ (arr.max() - arr.min())#формулка для нормализации
print(arr_norm)

[[0.53470315 0.75380312 0.09084821 0.94701067 0.07899898 1.
  0.14029333]
 [0.13027597 0.73349077 0.25307568 0.62706467 0.41378825 0.28173779
  0.43816621]
 [0.14551557 0.97523673 0.26513532 0.52283074 0.92945416 0.75223041
  0.85887942]
 [0.88014418 0.06902937 0.42908485 0.11550032 0.         0.40349089
  0.84048489]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
arr = np.random.randint(0, 10, (8, 10))
min_len = sum(arr[0])
ind = 0
for i in range(1, len(arr)):
    if min_len > sum(arr[i]):
        min_len = sum(arr[i])
        ind = i
print(ind, arr[ind])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np
from numpy.linalg import norm
vector1 = np.random.randint(0, 10, (1, 10))
vector2 = np.random.randint(0, 10, (1, 10))
a = norm(vector1 - vector2)#функция для вычисления евклидова расстояния
print(vector1)
print(vector2)
print(a)

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
minus_c = np.dot(c, -1)#умножение матриц
a_inv = np.linalg.inv(a)#обратная матрица
b_inv = np.linalg.inv(b)
x1 = np.dot(a_inv, minus_c)
x = np.dot(x1, b_inv)
print(x)

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)#запись в arr массива из файла
print(arr[:5])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
print(np.min(arr[:, 1], axis=0), np.max(arr[:, 1], axis=0), np.mean(arr[:, 1]), np.median(arr[:, 1]))#mean = ср. знач. median - ср. элем.
print(np.min(arr[:, 2], axis=0), np.max(arr[:, 2], axis=0), np.mean(arr[:, 2]), np.median(arr[:, 2]))

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [12]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
q = np.quantile(arr[:,1], 0.75)
# все значения больше значения квантиля = 65 заменим на 65
# numpy.where(condition, [x, y, ]/) - когда conditon True - x, иначе y
arr[:, 1] = np.where(arr[:, 1] > q, q, arr[:, 1])  
print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
cnt = 0
print(len(arr) * len(arr[0]) - np.count_nonzero(arr))
arr[arr == 0] = 1
print(len(arr) * len(arr[0]) - np.count_nonzero(arr))

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
cnt = len(np.unique(np.column_stack([arr[:,1], arr[:,2]]), axis=0))
print(cnt)

4195


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [9]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
uniq = np.unique(arr[:,2])
print(uniq, len(uniq))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
mas = arr[arr[:, 2] <= 5]
print(mas)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [1]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
arr[arr[:, 1] == 0] = 1
mas = arr[:, 2] / arr[:, 1]
summa = np.sum(mas)
itog = summa / len(mas)
print(itog)
print(f"max: {mas.max()}")

0.3429242617056809
max: 23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [7]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
arr = (arr[arr[:, 1].argsort()[::-1]])[:100]
summa = np.sum(arr[:,2])
print(summa / 100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [6]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
np.random.shuffle(arr)#перемешиваем
print(arr[:10])

[[126971     75     10]
 [  4667      0      5]
 [123456     75      9]
 [100014    270      7]
 [  8038     15     11]
 [ 19188     30     13]
 [150192     45      6]
 [488628     20      6]
 [176133     60     17]
 [198446     70     15]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [5]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
sr = np.mean(arr[:, 2])
cnt = np.sum(arr[: ,2] < sr)
print(f"{cnt / len(arr) * 100} %")

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [4]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
simple_recipe = np.where((arr[:, 1] <= 20) & (arr[:, 2] <= 5), 1, 0)#новый столбец, где 1 если простой и 0 если не простой
arr = np.column_stack((arr, simple_recipe))#добавляем новый столбец
print(arr)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [2]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
simple_recipe = np.where((arr[:, 1] <= 20) & (arr[:, 2] <= 5), 1, 0)
arr = np.column_stack((arr, simple_recipe))
cnt = np.sum(arr[:, 3] == 1)
print(f"{cnt/len(arr) * 100} %")

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [3]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

short = arr[arr[:, 1] < 10]
standard= arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
long = arr[arr[:, 1] >= 20]#разделяем

max_znach= min(len(short), len(standard), len(long))#максимальное количество рецептов в каждой группе
short = short[:max_znach]
standard = standard[:max_znach]
long = long[:max_znach]#срезаем, т.к. массив должен быть только прямоугольным

array = np.array([short, standard, long])
print(array.shape)

(3, 7588, 3)
